- name: Deploy infrastructure, phase 1
  terraform:
    project_path: ./terraform/nutanix/phase-1
    state: present
    force_init: true
    variables:
      username: "{{username}}"
      password: "{{password}}"
      endpoint: "{{endpoint}}"
      subnet: "{{subnet}}"

- name: Move state to next stage
  copy:
    src: ./terraform/nutanix/phase-1/terraform.tfstate
    dest: ./terraform/nutanix/phase-2/terraform.tfstate

- name: Deploy infrastructure, phase 2
  terraform:
    project_path: ./terraform/nutanix/phase-2
    state: present
    force_init: false
    variables:
      username: "{{username}}"
      password: "{{password}}"
      endpoint: "{{endpoint}}"
      subnet: "{{subnet}}"

- name: Move state to next stage
  copy:
    src: ./terraform/nutanix/phase-2/terraform.tfstate
    dest: ./terraform/nutanix/phase-3/terraform.tfstate

- name: Deploy infrastructure, phase 3
  terraform:
    project_path: ./terraform/nutanix/phase-3
    state: present
    force_init: false
    variables:
      username: "{{username}}"
      password: "{{password}}"
      endpoint: "{{endpoint}}"
      subnet: "{{subnet}}"
  register: terraform_out

- name: Add DB node to ansible
  add_host:
    hostname: sfdb
    ansible_ssh_host: "{{terraform_out.outputs.sfdb.value}}"
    groups: db

- name: Add DB node_ip
  set_fact:
    node_ip: "{{terraform_out.outputs.sfdb.value}}"
  delegate_to: sfdb
  delegate_facts: true

- name: Add sf-1 to ansible
  add_host:
    hostname: sf-1
    ansible_ssh_host: "{{terraform_out.outputs.sf_1.value}}"
    groups: hypervisors

- name: Add sf-1 node_ip
  set_fact:
    node_ip: "{{terraform_out.outputs.sf_1.value}}"
  delegate_to: sf-1
  delegate_facts: true

- name: Add sf-2 to ansible
  add_host:
    hostname: sf-2
    ansible_ssh_host: "{{terraform_out.outputs.sf_2.value}}"
    groups: hypervisors

- name: Add sf-2 node_ip
  set_fact:
    node_ip: "{{terraform_out.outputs.sf_2.value}}"
  delegate_to: sf-2
  delegate_facts: true

- name: Log terraform hosts
  debug:
    msg:
      - "db: {{hostvars['sfdb']['ansible_ssh_host']}}, {{hostvars['sfdb']['node_ip']}}"
      - "sf-1: {{hostvars['sf-1']['ansible_ssh_host']}}, {{hostvars['sf-1']['node_ip']}}"
      - "sf-2: {{hostvars['sf-2']['ansible_ssh_host']}}, {{hostvars['sf-2']['node_ip']}}"
