--- # Install shakenfist on a series of Ubuntu machines
- hosts: localhost
  gather_facts: yes
  connection: ssh
  vars_files:
    - vars

  tasks:
    - name: Ensure unit tests pass
      shell: tox -epy37

    - name: Clear out old wheels
      shell:
        cmd: rm *.whl *.tar.gz
        chdir: ../dist

    - name: Build a wheel for shakenfist
      shell:
        cmd: python3 setup.py sdist bdist_wheel
        chdir: ..

    - name: Find the most recent wheel for shakenfist
      shell: ls -rt ../dist/*.whl | tail -1 | sed 's/\.\.\/dist\///'
      register: wheel_complex

    - name: Extract wheel filename
      set_fact:
        wheel_path: "{{wheel_complex.stdout}}"

    - name: Log wheel details
      debug:
        msg: "Wheel is: {{hostvars['localhost']['wheel_path']}}"

    - include: terraform/{{cloud}}/terraform.yml

    - name: Wait for instances to boot
      pause:
        minutes: "{{bootdelay}}"

- hosts: allsf
  any_errors_fatal: true
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  vars_files:
    - vars

  tasks:
    - include: includes/debian.yml

- hosts: hypervisors
  any_errors_fatal: true
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  vars_files:
    - vars

  tasks:
    - name: Check that we can run KVM
      shell: kvm-ok

    - include: terraform/{{cloud}}/postboot.yml

- hosts: allsf
  any_errors_fatal: true
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  vars_files:
    - vars

  tasks:
    - include: includes/python3.yml

    - name: Make /srv/shakenfist/
      file:
        path: /srv/shakenfist
        state: directory
        mode: "0755"

    - name: Ensure the source directory is absent
      file:
        path: /srv/shakenfist/src/
        state: absent

    - name: Copy shakenfist
      synchronize:
        src: ../dist/{{hostvars['localhost']['wheel_path']}}
        dest: /srv/shakenfist/

    - name: Uninstall shakenfist, if present
      command: pip3 uninstall -y shakenfist
      ignore_errors: True

    - name: Install shakenfist
      command: pip3 install {{hostvars['localhost']['wheel_path']}}
      args:
        chdir: /srv/shakenfist/

    - name: Create config directory
      file:
        path: /etc/sf
        state: directory
        mode: "0755"

    - name: Determine default interface
      shell: ip route list default | head -1 | cut -f 5 -d " "
      register: node_egress_nic_complex
      when: node_egress_nic is not defined

    - name: Extract node default interface
      set_fact:
        node_egress_nic: "{{node_egress_nic_complex.stdout}}"
      when: node_egress_nic is not defined

    - name: Write sfrc file
      template:
        src: files/sfrc
        dest: /etc/sf/sfrc
        owner: root
        group: sudo
        mode: u=rwx,g=rwx,o=

- hosts: db
  any_errors_fatal: true
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh

  vars_files:
    - vars

  tasks:
    - include: includes/docker.yml

    - name: Create a etcd user
      user:
        name: sfetcd
        comment: shakenfist etcd
        group: daemon
      register: sfetcd_user_complex

    - name: Test if we have an etcd
      shell: docker inspect sfetcd
      ignore_errors: True
      register: has_sfetcd

    - name: Make /srv/shakenfist/etcd
      file:
        path: /srv/shakenfist/etcd
        state: directory
        owner: sfetcd
        mode: u=rwx,g=,o=
      when: has_sfetcd.rc == 1

    - name: Fix etcd permissions
      file:
        path: /srv/shakenfist/etcd
        recurse: true
        owner: sfetcd
        mode: u=rwx,g=,o=
      when: has_sfetcd.rc == 1

    - name: Write etcd configuration file
      template:
        src: files/etcd.conf
        dest: /srv/shakenfist/etcd.conf.yml
        owner: sfetcd
        group: sudo
        mode: u=r,g=r,o=
      when: has_sfetcd.rc == 1

    - name: Create etcd docker container
      docker_container:
        name: sfetcd
        image: bitnami/etcd
        restart_policy: always
        volumes:
          - /srv/shakenfist/etcd:/data
          - /srv/shakenfist/etcd.conf.yml:/opt/bitnami/etcd/conf/etcd.conf.yml
        ports:
          - 0.0.0.0:2379:2379
          - 0.0.0.0:2380:2380
        env:
          ETCD_ROOT_PASSWORD: "{{db_root_password}}"
        user: "{{sfetcd_user_complex.uid}}"
      when: has_sfetcd.rc == 1

    - name: Create etcd user
      shell: ETCDCTL_API=3 etcdctl --user="root:{{db_root_password}}" user add "sf:{{db_user_password}}"
      when: has_sfetcd.rc == 1

    - name: Give etcd user root permissions
      shell: ETCDCTL_API=3 etcdctl --user="root:{{db_root_password}}" user grant sf root
      when: has_sfetcd.rc == 1

    - name: Create a prometheus user
      user:
        name: sfprometheus
        comment: shakenfist prometheus
        group: daemon
      register: sfprometheus_user_complex

    - name: Test if we have a prometheus
      shell: docker inspect sfprom
      ignore_errors: True
      register: has_sfprom

    - name: Stop prometheus if running
      shell: docker stop sfprom
      when: has_sfprom.rc == 0

    - name: Make /srv/shakenfist/prometheus
      file:
        path: /srv/shakenfist/prometheus
        state: directory
        owner: sfprometheus
        mode: u=rwx,g=,o=

    - name: Fix prometheus permissions
      file:
        path: /srv/shakenfist/prometheus
        recurse: true
        owner: sfprometheus
        mode: u=rwx,g=,o=

    - name: Write prometheus configuration file
      copy:
        content: |
          global:
            external_labels:
              monitor: 'shakenfist'

          scrape_configs:
            - job_name: 'node'
              static_configs:
                - targets: [
                      {% for svr in groups.allsf %}
                        '{{hostvars[svr]['node_ip']}}:9100',
                      {% endfor %}
                    ]
            - job_name: 'shakenfist'
              static_configs:
                - targets: [
                      {% for svr in groups.hypervisors %}
                        '{{hostvars[svr]['node_ip']}}:13001',
                      {% endfor %}
                    ]
        dest: /srv/shakenfist/prometheus/prometheus.yml
        owner: sfprometheus
        mode: u=rwx,g=,o=

    - name: Create prometheus docker container
      docker_container:
        name: sfprom
        image: prom/prometheus
        restart_policy: always
        volumes:
          - /srv/shakenfist/prometheus:/prometheus
          - /srv/shakenfist/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
          - 0.0.0.0:9090:9090
        user: "{{sfprometheus_user_complex.uid}}"

    - name: Create a grafana user
      user:
        name: sfgrafana
        comment: shakenfist grafana
        group: daemon
      register: sfgrafana_user_complex

    - name: Test if we have a grafana
      shell: docker inspect sfgrafana
      ignore_errors: True
      register: has_sfgrafana

    - name: Stop grafana if running
      shell: docker stop sfgrafana
      when: has_sfgrafana.rc == 0

    - name: Make /srv/shakenfist/grafana
      file:
        path: /srv/shakenfist/grafana
        state: directory
        owner: sfgrafana
        mode: u=rwx,g=,o=

    - name: Make /srv/shakenfist/grafana/data
      file:
        path: /srv/shakenfist/grafana/data
        state: directory
        owner: sfgrafana
        mode: u=rwx,g=,o=

    - name: Make /srv/shakenfist/grafana/logs
      file:
        path: /srv/shakenfist/grafana/logs
        state: directory
        owner: sfgrafana
        mode: u=rwx,g=,o=

    - name: Make /srv/shakenfist/grafana/dashboards
      file:
        path: /srv/shakenfist/grafana/dashboards
        state: directory
        owner: sfgrafana
        mode: u=rwx,g=,o=

    - name: Write grafana dashboard
      copy:
        src: files/grafana.json
        dest: /srv/shakenfist/grafana/dashboards/shakenfist.json
        owner: sfgrafana
        mode: u=rwx,g=,o=

    - name: Copy grafana config
      synchronize:
        src: files/grafana/
        dest: /srv/shakenfist/grafana/config

    - name: Fix grafana permissions
      file:
        path: /srv/shakenfist/grafana
        recurse: true
        owner: sfgrafana
        mode: u=rwx,g=,o=

    - name: Write prometheus grafana configuration file
      copy:
        content: |
          apiVersion: 1

          datasources:
          - name: Prometheus
            type: prometheus
            orgId: 1
            url: http://{{node_ip}}:9090
            isDefault: true
            version: 1
            editable: false
            access: proxy
            jsonData:
              tlsSkipVerify: true
        dest: /srv/shakenfist/grafana/config/provisioning/datasources/prometheus.yml
        owner: sfgrafana
        mode: u=rwx,g=,o=

    - name: Create grafana docker container
      docker_container:
        name: sfgrafana
        image: grafana/grafana
        restart_policy: always
        volumes:
          - /srv/shakenfist/grafana/data:/var/lib/grafana
          - /srv/shakenfist/grafana/logs:/var/log/grafana
          - /srv/shakenfist/grafana/dashboards:/var/lib/grafana/dashboards
          - /srv/shakenfist/grafana/config:/etc/grafana
        env:
          GF_SECURITY_ADMIN_PASSWORD: "{{db_user_password}}"
        ports:
          - 3000:3000
        user: "{{sfgrafana_user_complex.uid}}"

    - name: Write syslog file
      template:
        src: files/rsyslog-server-01-sf.conf
        dest: /etc/rsyslog.d/01-sf.conf
        owner: root
        group: sudo
        mode: u=r,g=r,o=

    - name: Restart syslog
      service:
        name: rsyslog
        enabled: yes
        state: restarted

- hosts: hypervisors
  any_errors_fatal: true
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  vars_files:
    - vars

  tasks:
    - name: Syslog server is DB server
      set_fact:
        syslog: "{{hostvars['localhost']['database_node_ip']}}"

    - name: Write syslog file
      template:
        src: files/rsyslog-client-01-sf.conf
        dest: /etc/rsyslog.d/01-sf.conf
        owner: root
        group: sudo
        mode: u=r,g=r,o=

    - name: Restart syslog
      service:
        name: rsyslog
        enabled: yes
        state: restarted

    - name: Create storage directory
      file:
        path: /srv/shakenfist
        state: directory
        mode: "0755"

    - name: Copy libvirt template
      copy:
        src: files/libvirt.tmpl
        dest: /srv/shakenfist/libvirt.tmpl
        owner: root
        group: root
        mode: "0644"

    - name: Turn off default libvirt networking
      shell: |
        virsh net-destroy default
      ignore_errors: True

    - name: Copy dhcp config template
      copy:
        src: files/dhcp.tmpl
        dest: /srv/shakenfist/dhcp.tmpl
        owner: root
        group: root
        mode: "0644"

    - name: Copy dhcp hosts template
      copy:
        src: files/dhcphosts.tmpl
        dest: /srv/shakenfist/dhcphosts.tmpl
        owner: root
        group: root
        mode: "0644"

    - name: Determine node IP
      shell: /usr/bin/dig @resolver1.opendns.com ANY myip.opendns.com +short
      register: node_ip_complex
      when: node_ip is not defined

    - name: Extract node IP
      set_fact:
        node_ip: "{{node_ip_complex.stdout}}"
      when: node_ip is not defined

    - name: Write systemd unit
      template:
        src: files/sf.service
        dest: /lib/systemd/system
        owner: root
        group: root
        mode: u=r,g=r,o=r

    - name: Start the SF daemon
      service:
        name: sf
        enabled: yes
        state: restarted

    - name: Fetch terraform
      shell: wget https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip -O /tmp/terraform.zip

    - name: Extract terraform
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Copy terraform provider
      copy:
        src: ../golang/terraform-provider-shakenfist/terraform-provider-shakenfist
        dest: /root/terraform-provider-shakenfist
        owner: root
        group: root
        mode: u=rx,g=rx,o=rx
