- hosts: hypervisors
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  vars_files:
    - vars

  tasks:
    - name: Clear out old instances and networks
      shell: |
        for inst in `sf-client --no-pretty instance list | grep -v uuid | cut -f 1 -d ","`
        do
          sf-client --no-pretty instance delete $inst
        done

        for net in `sf-client --no-pretty network list | grep -v uuid | cut -f 1 -d ","`
        do
          sf-client --no-pretty network delete $net
        done
      run_once: true

    - name: We should have an empty list of networks
      shell: |
        [ `sf-client --no-pretty network list | wc -l` -eq 1 ]

    - name: We should have an empty list of instances
      shell: |
        [ `sf-client --no-pretty instance list | wc -l` -eq 1 ]

    - name: Create a network
      shell: |
        sf-client --no-pretty network create 192.168.242.0/24
      run_once: true

    - name: Determine network uuid
      shell: |
        sf-client --no-pretty network list | grep 192.168.242.0/24 | cut -f 1 -d ","
      register: network_uuid_complex

    - name: Extract network uuid
      set_fact:
        network_uuid: "{{network_uuid_complex.stdout}}"

    - name: Log network uuid
      debug:
        msg: Network uuid is {{network_uuid}}.

- hosts: sf-1
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  vars_files:
    - vars

  tasks:
    - name: We shouldn't have any VMs running
      shell: |
        [ `virsh list | grep running | wc -l` -eq 0 ]

    - name: And there should be no containers
      shell: |
        [ `docker ps | wc -l` -eq 1 ]

    - name: Start an instance on sf-1
      shell: |
        sf-client --no-pretty instance create "{{network_uuid}}" inst-1 1 1 8@cirros

- hosts: sf-2
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  vars_files:
    - vars

  tasks:
    - name: We shouldn't have any VMs running
      shell: |
        [ `virsh list | grep running | wc -l` -eq 0 ]

    - name: And there should be no containers
      shell: |
        [ `docker ps | wc -l` -eq 1 ]

    - name: Start an instance on sf-2
      shell: |
        sf-client --no-pretty instance create "{{network_uuid}}" inst-2 1 1 8@cirros

- hosts: hypervisors
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  vars_files:
    - vars

  tasks:
    - name: We should have two instances
      shell: |
        [ `sf-client --no-pretty instance list | wc -l` -eq 3 ]

    - name: With one recorded on sf-1
      shell: |
        [ `sf-client --no-pretty instance list | grep sf-1 | wc -l` -eq 1 ]

    - name: And one recorded on sf-2
      shell: |
        [ `sf-client --no-pretty instance list | grep sf-2 | wc -l` -eq 1 ]
