# Fake terraform for hard coded metal

- name: Add sf-1 to ansible
  add_host:
    hostname: sf-1
    ansible_ssh_host: "10.1.1.100"
    groups:
      - hypervisors
      - db

- name: Add sf-1 node_ip
  set_fact:
    node_ip: "10.1.1.100"
  delegate_to: sf-1
  delegate_facts: true

- name: Add sf-2 to ansible
  add_host:
    hostname: sf-2
    ansible_ssh_host: "10.1.1.102"
    groups: hypervisors

- name: Add sf-2 node_ip
  set_fact:
    node_ip: "10.1.1.102"
  delegate_to: sf-2
  delegate_facts: true

- name: Log terraform hosts
  debug:
    msg:
      - "sf-1: {{hostvars['sf-1']['ansible_ssh_host']}}, {{hostvars['sf-1']['node_ip']}}"
      - "sf-2: {{hostvars['sf-2']['ansible_ssh_host']}}, {{hostvars['sf-2']['node_ip']}}"
